fix error in static analysing code PSALM (#38)
ERROR: UndefinedDocblockClass:
Docblock-defined class or interface Hemp\Presenter\Hemp\Presenter does not exist